#include "coffee_model.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

static coffee_data_t d, candidate, loaded;
static uint8_t wire[COFFEE_WIRE_MAX];
int main(void)
{
    assert(coffee_month_days(2000, 2) == 29 && coffee_month_days(2100, 2) == 28);
    assert(coffee_date_valid(20240229) && !coffee_date_valid(20230229));
    assert(!coffee_date_valid(20191231) && !coffee_date_valid(21000101));
    assert(coffee_date_step(20240228, 1) == 20240229);
    assert(coffee_date_step(20240229, 1) == 20240301);
    assert(coffee_date_step(20260101, -1) == 20251231);
    assert(coffee_date_step(20200101, -1) == 20200101);
    assert(coffee_date_month(20260131, 1) == 20260228);
    assert(coffee_date_month(20240331, -1) == 20240229);
    assert(coffee_weekday(20261006) == 1 && coffee_weekday(20240229) == 3);
    coffee_data_init(&d, 20261006);
    coffee_model_t m;
    coffee_model_init(&m, &d);
    assert(!m.clock_valid && m.page == COFFEE_HOME);
    assert(coffee_model_key(&m, COFFEE_OK, 0) == COFFEE_ACTION_NONE && m.page == COFFEE_RECORD);
    assert(coffee_model_key(&m, COFFEE_OK, 0) == COFFEE_ACTION_NONE && m.page == COFFEE_DATE);
    m.date_field = 5;
    assert(coffee_model_key(&m, COFFEE_OK, 0) == COFFEE_ACTION_CLOCK);
    assert(coffee_prepare_change(&m, COFFEE_ACTION_CLOCK, &candidate));
    d = candidate;
    coffee_model_complete(&m, COFFEE_ACTION_CLOCK, true);
    assert(m.page == COFFEE_RECORD);
    assert(m.manually_set);
    assert(coffee_model_key(&m, COFFEE_OK, 0) == COFFEE_ACTION_RECORD);
    assert(coffee_prepare_change(&m, COFFEE_ACTION_RECORD, &candidate));
    assert(d.count == 0 && candidate.count == 1 && candidate.entries[0].manual_time);
    coffee_model_complete(&m, COFFEE_ACTION_RECORD, false);
    assert(m.page == COFFEE_RECORD && m.notice == COFFEE_NOTICE_FAILED && d.count == 0);
    d = candidate;
    coffee_model_complete(&m, COFFEE_ACTION_RECORD, true);
    assert(m.page == COFFEE_HOME && coffee_day_count(&d, 20261006) == 1);
    coffee_model_clock(&m, 20261007, 1439, true);
    assert(m.clock_valid && m.now_date == 20261007);
    m.page = COFFEE_RECORD; m.type = COFFEE_LATTE; m.draft_date = 20261007; m.draft_minute = 1439;
    m.manually_set = false; m.recipe = COFFEE_NO_RECIPE;
    assert(coffee_prepare_change(&m, COFFEE_ACTION_RECORD, &candidate));
    d = candidate;
    assert(coffee_day_entry(&d, 20261007, 0) == 1 && coffee_day_entry(&d, 20261007, 1) == -1);
    assert(coffee_month_count(&d, 20261007) == 2);
    size_t n = coffee_encode(&d, wire, sizeof(wire));
    assert(n > 0 && coffee_decode(&loaded, wire, n));
    assert(loaded.count == 2 && loaded.entries[1].type == COFFEE_LATTE && loaded.entries[1].minute == 1439);
    assert(!coffee_encode(&d, wire, n - 1));
    assert(!coffee_decode(&loaded, wire, n - 1));
    wire[n - 1] ^= 1; assert(!coffee_decode(&loaded, wire, n));
    assert(coffee_encode(&d, wire, sizeof(wire)) == n);
    wire[4] = 99; assert(!coffee_decode(&loaded, wire, n));
    coffee_data_init(&d, 20261006);
    d.count = COFFEE_CAPACITY;
    for (unsigned i = 0; i < d.count; ++i) d.entries[i] = (coffee_entry_t){20261006, 0, 0, COFFEE_HAND, COFFEE_NO_RECIPE, 0};
    assert(!coffee_prepare_change(&m, COFFEE_ACTION_RECORD, &candidate));
    m.cursor = 20261006; m.day_focus = 0;
    assert(coffee_prepare_change(&m, COFFEE_ACTION_DELETE, &candidate));
    assert(candidate.count == COFFEE_CAPACITY - 1 && d.count == COFFEE_CAPACITY);
    n = coffee_encode(&d, wire, sizeof(wire)); assert(n <= sizeof(wire) && coffee_decode(&loaded, wire, n));
    coffee_data_init(&d, 20261006); coffee_model_init(&m, &d);
    m.page = COFFEE_RECIPE; m.recipe = 0; m.focus = 0;
    coffee_model_key(&m, COFFEE_OK, 1000);
    assert(m.page == COFFEE_TIMER && coffee_timer_seconds(&m, 31000) == 30);
    assert(coffee_timer_stage(&m, 31000) == 1);
    coffee_model_key(&m, COFFEE_OK, 31000);
    assert(m.timer_paused && coffee_timer_seconds(&m, 91000) == 30);
    coffee_model_clock(&m, 20261101, 60, true); /* SNTP/wall-clock jump */
    coffee_model_key(&m, COFFEE_OK, 91000);
    assert(coffee_timer_seconds(&m, 121000) == 60);
    coffee_model_key(&m, COFFEE_UP, 121000);
    assert(m.page == COFFEE_RECORD && m.record_seconds == 60 && !m.timer_active);
    coffee_model_key(&m, COFFEE_BACK, 122000);
    assert(m.page == COFFEE_HOME);
    m.page = COFFEE_EDIT_RECIPE; m.recipe = 0; m.draft_recipe = d.recipes[0];
    m.focus = 0; coffee_model_key(&m, COFFEE_OK, 0); coffee_model_key(&m, COFFEE_DOWN, 0);
    assert(m.draft_recipe.grams == 16 && m.editing);
    coffee_model_key(&m, COFFEE_OK, 0); m.focus = 4;
    assert(coffee_model_key(&m, COFFEE_OK, 0) == COFFEE_ACTION_RECIPE);
    assert(coffee_prepare_change(&m, COFFEE_ACTION_RECIPE, &candidate) && candidate.recipes[0].grams == 16);
    assert(coffee_stage_water(&candidate.recipes[0], 3) == 240);
    candidate.recipes[0].seconds = 0; assert(!coffee_recipe_valid(&candidate.recipes[0]));
    assert(!coffee_encode(&candidate, wire, sizeof(wire)));
    coffee_model_init(&m, &d);
    coffee_model_key(&m, COFFEE_OK, 0);
    coffee_model_clock(&m, 20271008, 615, true);
    assert(m.draft_date == 20271008 && m.draft_minute == 615);
    assert(coffee_prepare_change(&m, COFFEE_ACTION_RECORD, &candidate));
    assert(candidate.entries[0].date == 20271008 && !candidate.entries[0].manual_time);
    coffee_model_key(&m, COFFEE_PREV_MONTH, 0);
    m.date_field = 2; m.editing = true; coffee_model_key(&m, COFFEE_DOWN, 0);
    assert(m.draft_date == 20271009);
    coffee_model_key(&m, COFFEE_BACK, 0);
    assert(m.page == COFFEE_RECORD && m.draft_date == 20271008 && m.draft_minute == 615);
    assert(coffee_prepare_change(&m, COFFEE_ACTION_RECORD, &candidate) && !candidate.entries[0].manual_time);
    coffee_model_init(&m, &d);
    coffee_model_key(&m, COFFEE_OK, 0);
    coffee_model_key(&m, COFFEE_PREV_MONTH, 0);
    coffee_model_clock(&m, 20271009, 720, true);
    assert(!m.draft_clock_valid);
    coffee_model_key(&m, COFFEE_BACK, 0);
    assert(m.draft_clock_valid && m.draft_date == 20271009 && m.draft_minute == 720);
    assert(coffee_prepare_change(&m, COFFEE_ACTION_RECORD, &candidate) && !candidate.entries[0].manual_time);
    m.page = COFFEE_FORGET; m.focus = 0;
    assert(coffee_model_key(&m, COFFEE_OK, 0) == COFFEE_ACTION_NONE && m.page == COFFEE_SETTINGS);
    m.page = COFFEE_FORGET; m.focus = 1;
    assert(coffee_model_key(&m, COFFEE_OK, 0) == COFFEE_ACTION_FORGET);
    puts("Coffee dates/calendar, transactional records, versioned CRC codec, recipe and monotonic timer: PASS");
    return 0;
}
